# Generated by Django 2.2.7 on 2019-11-23 04:03

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=localflavor.us.models.USStateField(default='TX', max_length=2),
        ),
    ]
