# Generated by Django 2.2.7 on 2019-12-03 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0006_auto_20191202_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.Member'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
