# Generated by Django 2.2.7 on 2019-12-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0007_auto_20191202_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid_dues',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
